name: spacemate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management & Routing
  flutter_bloc: ^8.1.4
  go_router: ^10.1.2

  # Dependency Injection
  get_it: ^7.6.7
  injectable: ^2.1.5

  # Network
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1

  # Database
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2+1  # For desktop support
  path: ^1.8.3

  # Utils
  equatable: ^2.0.5
  intl: ^0.20.2
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  uuid: ^4.3.3
  logger: ^2.0.2+1

  # UI
  flutter_svg: ^2.0.10+1
  google_fonts: ^5.1.0
  dynamic_color: ^1.5.0
  material_symbols_icons: ^4.2665.0
  material_color_utilities: ^0.11.1
  flutter_onboarding_slider: ^1.0.11

  # Storage
  shared_preferences: ^2.2.1
  flutter_dotenv: ^5.1.0

  # File & Path
  path_provider: ^2.1.1
  path_provider_android: ^2.2.1
  path_provider_foundation: ^2.4.0
  path_provider_linux: ^2.2.1
  path_provider_windows: ^2.2.1
  path_provider_platform_interface: ^2.1.2
  flutter_downloader: ^1.11.6
  file_saver: ^0.3.0
  permission_handler: ^11.3.0

  # Localization
  flutter_localizations:
    sdk: flutter

  # Removed Hive dependencies
  # hive: any
  # hive_flutter: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mocktail: ^1.0.0
  mockito: ^5.4.4
  bloc_test: ^9.1.4
  mocktail_image_network: ^1.0.0
  test: ^1.24.0
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test_core: any
  test_api: any
  build_runner: ^2.4.8
  json_serializable: ^6.8.0
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - designs/
    - test/fixtures/
  fonts:
    - family: MaterialSymbols
      fonts:
        - asset: packages/material_symbols_icons/fonts/MaterialSymbolsOutlined.ttf
        - asset: packages/material_symbols_icons/fonts/MaterialSymbolsRounded.ttf
        - asset: packages/material_symbols_icons/fonts/MaterialSymbolsSharp.ttf
  
