name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        flutter: ["stable"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.flutter }}

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Analyze
        run: |
          flutter analyze

      - name: Run tests with coverage
        run: |
          flutter test --coverage

      - name: Upload lcov
        uses: actions/upload-artifact@v4
        with:
          name: lcov
          path: coverage/lcov.info

      - name: Generate coverage report (optional)
        if: always()
        run: |
          echo "Coverage artifact uploaded. Use GitHub Actions artifact or codecov to view details."
